name: darkblu_full
description: Aplicatia DarKblu - versiunea completa
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  provider: ^6.1.2
  http: ^0.13.6
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  video_player: ^2.7.0
  flutter_local_notifications: ^15.1.1

flutter:
  uses-material-design: true
